// Bundle the map engine locally: opening a map must never depend on a JS/CSS CDN.
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const leafletRoot = path.dirname(require.resolve('leaflet/package.json'));
const read = (file) => fs.readFileSync(file, 'utf8');
const engine = read(path.join(leafletRoot, 'dist/leaflet.js')).replace(/\/\/# sourceMappingURL=.*$/gm, '');
const css = read(path.join(leafletRoot, 'dist/leaflet.css'));
const license = read(path.join(leafletRoot, 'LICENSE'));
const mapDir = path.join(root, 'src/components/map');
const html = `<!DOCTYPE html>
<!-- Leaflet ${require('leaflet/package.json').version}\n${license} -->
<html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<meta name="referrer" content="strict-origin-when-cross-origin">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src https: data:; style-src 'unsafe-inline'; script-src 'unsafe-inline'">
<style>${css}\n${read(path.join(mapDir, 'map.css'))}</style></head>
<body><div id="map" aria-label="Explore nearby places"></div>
<div id="tile-error" role="status" hidden>Map tiles unavailable. <button id="retry" type="button">Retry</button></div>
<script>${engine}</script><script>${read(path.join(mapDir, 'runtime.js'))}</script></body></html>`;
const output = '// Generated by npm run map:build. Edit map.css / runtime.js, then regenerate.\n'
  + `export const mapHtml = ${JSON.stringify(html)};\n`;
const target = path.join(mapDir, 'mapDocument.generated.ts');
if (process.argv.includes('--check')) {
  if (!fs.existsSync(target) || read(target) !== output) {
    console.error('Map bundle is stale. Run npm run map:build.');
    process.exitCode = 1;
  }
} else {
  fs.writeFileSync(target, output);
  console.log(`Bundled Leaflet ${require('leaflet/package.json').version} and map runtime (${Buffer.byteLength(html)} bytes).`);
}
